import webbrowser

def generarHTML_MS(simbolos,Limite):
    f = open('MenuSimbolos.html','w')
    f.write('<html>\n')
    f.write('   <head>\n')
    f.write(' <title>Tabla Simbolos Menu</title>\n')
    f.write('<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>\n')
    f.write('<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">\n')
    f.write('<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>\n')
    f.write('<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/solid.css">\n')
    f.write('<script src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script>\n')
    f.write('   </head>\n')
    f.write('   <body>\n')
    f.write('<table class="table table-striped table-dark">\n')
    f.write('<thead>\n')
    f.write('<tr>\n')
    f.write('<th scope="col">No</th>\n')   
    f.write('<th scope="col">Lexema</th>\n')
    f.write('<th scope="col">Fila</th>\n')
    f.write('<th scope="col">Columna</th>\n')
    f.write('<th scope="col">Token</th>\n')
    f.write('</tr>\n')
    f.write('</thead>\n')
    f.write('<tbody>\n')

    for e in range(len(simbolos)):
        j = simbolos[e]
        f.write('<tr>\n')
        f.write('<th scope="row">'+str(e+1)+'</th>\n')
        f.write('<td>'+str(j.lexema)+'</td>\n')
        f.write('<td>'+str(j.fila)+'</td>\n')
        f.write('<td>'+str(j.columna)+'</td>\n')
        f.write('<td>'+j.tipo+'</td>\n')
        f.write('</tr>\n')
        
    f.write('</tbody>\n')
    f.write('</table>\n')
    f.write('</body>\n')
    f.write('</html>\n')
    
    f.close()

    webbrowser.open_new_tab('MenuSimbolos.html')

def generarHTML_MER(errores):
    f = open('ErroresMenu.html','w')
    f.write('<html>\n')
    f.write('   <head>\n')
    f.write(' <title>Tabla Errores Menu</title>\n')
    f.write('<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>\n')
    f.write('<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">\n')
    f.write('<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>\n')
    f.write('<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/solid.css">\n')
    f.write('<script src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script>\n')
    f.write('   </head>\n')
    f.write('   <body>\n')
    f.write('<table class="table table-striped table-dark">\n')
    f.write('<thead>\n')
    f.write('<tr>\n')
    f.write('<th scope="col">No</th>\n')   
    f.write('<th scope="col">Lexema</th>\n')
    f.write('<th scope="col">Descripcion</th>\n')
    f.write('<th scope="col">Fila</th>\n')
    f.write('<th scope="col">Columna</th>\n')
    f.write('</tr>\n')
    f.write('</thead>\n')
    f.write('<tbody>\n')

    for e in range(len(errores)):
        j = errores[e]
        f.write('<tr>\n')
        f.write('<th scope="row">'+str(e+1)+'</th>\n')
        f.write('<td>'+str(j.lexema)+'</td>\n')
        f.write('<td>'+j.descripcion+'</td>\n')
        f.write('<td>'+str(j.fila)+'</td>\n')
        f.write('<td>'+str(j.columna)+'</td>\n')
        f.write('</tr>\n')
        
    f.write('</tbody>\n')
    f.write('</table>\n')
    f.write('</body>\n')
    f.write('</html>\n')
    
    f.close()

    webbrowser.open_new_tab('ErroresMenu.html')

def generarHTML_FS(simbolos):
    f = open('FacturaSimbolos.html','w')
    f.write('<html>\n')
    f.write('   <head>\n')
    f.write(' <title>Tabla Simbolos Orden</title>\n')
    f.write('<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>\n')
    f.write('<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">\n')
    f.write('<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>\n')
    f.write('<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/solid.css">\n')
    f.write('<script src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script>\n')
    f.write('   </head>\n')
    f.write('   <body>\n')
    f.write('<table class="table table-striped table-dark">\n')
    f.write('<thead>\n')
    f.write('<tr>\n')
    f.write('<th scope="col">No</th>\n')   
    f.write('<th scope="col">Lexema</th>\n')
    f.write('<th scope="col">Fila</th>\n')
    f.write('<th scope="col">Columna</th>\n')
    f.write('<th scope="col">Token</th>\n')
    f.write('</tr>\n')
    f.write('</thead>\n')
    f.write('<tbody>\n')

    for e in range(len(simbolos)):
        j = simbolos[e]
        f.write('<tr>\n')
        f.write('<th scope="row">'+str(e+1)+'</th>\n')
        f.write('<td>'+str(j.lexema)+'</td>\n')
        f.write('<td>'+str(j.fila)+'</td>\n')
        f.write('<td>'+str(j.columna)+'</td>\n')
        f.write('<td>'+j.tipo+'</td>\n')
        f.write('</tr>\n')
        
    f.write('</tbody>\n')
    f.write('</table>\n')
    f.write('</body>\n')
    f.write('</html>\n')
    
    f.close()

    webbrowser.open_new_tab('FacturaSimbolos.html')

def generarHTML_FER(errores):
    f = open('ErroresFactura.html','w')
    f.write('<html>\n')
    f.write('   <head>\n')
    f.write(' <title>Tabla Errores Orden</title>\n')
    f.write('<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>\n')
    f.write('<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">\n')
    f.write('<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>\n')
    f.write('<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/solid.css">\n')
    f.write('<script src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script>\n')
    f.write('   </head>\n')
    f.write('   <body>\n')
    f.write('<table class="table table-striped table-dark">\n')
    f.write('<thead>\n')
    f.write('<tr>\n')
    f.write('<th scope="col">No</th>\n')   
    f.write('<th scope="col">Lexema</th>\n')
    f.write('<th scope="col">Descripcion</th>\n')
    f.write('<th scope="col">Fila</th>\n')
    f.write('<th scope="col">Columna</th>\n')
    f.write('</tr>\n')
    f.write('</thead>\n')
    f.write('<tbody>\n')
    for e in range(len(errores)):
        j = errores[e]
        f.write('<tr>')
        f.write('<td>'+str(e+1)+'</td>\n')
        f.write('<td>'+str(j.lexema)+'</td>\n')
        f.write('<td>'+j.descripcion+'</td>\n')
        f.write('<td>'+str(j.fila)+'</td>\n')
        f.write('<td>'+str(j.columna)+'</td>\n')
        f.write('</tr>')
    f.write('</tbody>')
    f.write('</table>')
    f.write('</body>\n')
    f.write('</html>\n')
    
    f.close()

    webbrowser.open_new_tab('ErroresFactura.html')

def generarArbol(simbolos):
    for s in simbolos:
        print(s.lexema + s.tipo)
